syscfg: Add _gov_schedutil()
Signed-off-by: Dimitar Yurukov <mscalindt@gmail.com>

diff --git a/syscfg b/syscfg
--- a/syscfg
+++ b/syscfg
@@ -5392,6 +5392,38 @@ SCALING_GOVERNOR
     done
 }
 
+_gov_schedutil() {
+    FILE_PATH_fd1 \
+<<'CPU'
+/sys/devices/system/cpu
+CPU
+
+    if ! loc_exists "$FILE_PATH"/cpu0/cpufreq/scaling_governor; then
+        ENOENT;
+        err -r -- 'F '; err - - "$FILE_PATH"/cpu0/cpufreq/scaling_governor
+        exit 202
+    fi
+
+    for core in "$FILE_PATH"/cpu*/cpufreq/scaling_governor; do
+        FILE_PATH_fd1 \
+<<SCALING_GOVERNOR
+$core
+SCALING_GOVERNOR
+
+        FILE_fd1 \
+<<'SCALING_GOVERNOR'
+schedutil
+SCALING_GOVERNOR
+
+        __file_write_overwrite;
+
+        if ! file_equiv "$FILE_PATH" "$FILE"; then
+            EERROR 'Failed to set the governor:'
+            err -r -- 'F '; err - - "$FILE_PATH"
+        fi
+    done
+}
+
 # "Removable" GRUB UEFI installation (NVRAM-less... when no NVRAM entries)
 _grub() {
     is_uefi || EERROR 'Not in UEFI mode.'
@@ -9418,6 +9450,7 @@ main() {
     ops="$ops gai-conf"
     ops="$ops git-conf"
     ops="$ops gov-performance"
+    ops="$ops gov-schedutil"
     ops="$ops grub grub-conf"
     ops="$ops gtk-conf"
     ops="$ops hostname"
