syscfg: Add rc()
"Print the return code of a command"

Signed-off-by: Dimitar Yurukov <mscalindt@gmail.com>

diff --git a/syscfg b/syscfg
--- a/syscfg
+++ b/syscfg
@@ -673,6 +673,28 @@ octal_decode() {
 }
 
 #! .desc:
+# Print the return code of a command
+#! .params:
+# <"$1"> - command
+# ["$2"+] - arguments
+#! .rc:
+# (0) success
+# (127) command does not exist
+# (255) bad input
+rc() {
+    args_min 1 "$#" || return 255
+
+    if cmd "$1"; then
+        "$@" > /dev/null 2>&1
+        printf "%d" "$?"
+    else
+        return 127
+    fi
+
+    return 0
+}
+
+#! .desc:
 # Replace specific character(s) with character(s) in a given string
 #! .params:
 # <"$1"> - specific character(s)
