syscfg: Add __loc_chown()
Signed-off-by: Dimitar Yurukov <mscalindt@gmail.com>

diff --git a/syscfg b/syscfg
--- a/syscfg
+++ b/syscfg
@@ -2952,6 +2952,80 @@ __loc_chmod() {
 }
 
 #! .desc:
+# Set owner of a file/directory
+#! .params:
+# <$1> - owner
+#! .uses:
+# <FILE_PATH> $ - the file/directory
+#! .rc:
+# (0) success
+# (*) error
+# (255) bad input/usage
+__loc_chown() {
+    args_eq 1 "$#" || return 255
+
+    if [ ! "$FILE_PATH" ]; then
+        err -r -1 'Missing FILE_PATH.'
+        return 255
+    fi
+
+    if ! loc_exists "$FILE_PATH"; then
+        ENOENT;
+        err -r -- 'F/D '; err - - "$FILE_PATH"
+        exit 202
+    fi
+
+    if [ -d "$FILE_PATH" ]; then
+        :
+    elif [ -f "$FILE_PATH" ]; then
+        :
+    else
+        EINVAL;
+        if [ -b "$FILE_PATH" ]; then
+            err -r -- 'B ' # block file
+        elif [ -c "$FILE_PATH" ]; then
+            err -r -- 'C ' # character file
+        elif [ -h "$FILE_PATH" ]; then
+            err -r -- 'L ' # symbolic link
+        elif [ -p "$FILE_PATH" ]; then
+            err -r -- 'P ' # named pipe
+        elif [ -S "$FILE_PATH" ]; then
+            err -r -- 'S ' # socket
+        elif [ -t "$FILE_PATH" ]; then
+            err -r -- 'FD ' # open file descriptor
+        elif [ -e "$FILE_PATH" ]; then
+            err -r -- '> '
+        fi
+        err - - "$FILE_PATH"
+        exit 222
+    fi
+
+    chattr_remove "$FILE_PATH"
+
+    if [ "$logging" = 1 ]; then
+        if [ "$(id -gn "$user")" = "$user" ]; then
+            if ! chown -R "$user":"$user" "$FILE_PATH"; then
+                EPERMS "$FILE_PATH"
+            fi
+        else
+            if ! chown -R "$user" "$FILE_PATH"; then
+                EPERMS "$FILE_PATH"
+            fi
+        fi
+    else
+        if [ "$(id -gn "$user")" = "$user" ]; then
+            if ! chown -R "$user":"$user" "$FILE_PATH" > /dev/null 2>&1; then
+                EPERMS "$FILE_PATH"
+            fi
+        else
+            if ! chown -R "$user" "$FILE_PATH" > /dev/null 2>&1; then
+                EPERMS "$FILE_PATH"
+            fi
+        fi
+    fi
+}
+
+#! .desc:
 # Remove a file/directory from the specified path
 #! .uses:
 # <FILE_PATH> $ - the file/directory
