syscfg: Remove errF()
Since upstream (`shell-glossary`) removed it, we also remove it.
Seamless removal; nothing should be affected.

Signed-off-by: Dimitar Yurukov <mscalindt@protonmail.com>

diff --git a/src/syscfg b/src/syscfg
--- a/src/syscfg
+++ b/src/syscfg
@@ -309,93 +309,6 @@ err() {
 }
 
 #! .desc:
-# Print red-colored formatted text to stderr and exit
-#! .params:
-# <$1> - exit code
-# <$2> - type(
-#     '-' - raw
-#     '--' - raw, no newline
-#     '-1' - %H%M%S date fmt
-#     '-2' - %H%M%S date fmt, no newline
-#     .
-# )
-# <"$3"+> - text
-#! .uses:
-# [NO_COLOR] $ - this environment variable disables colored output
-#! .rc:
-# (*) success
-# (255) bad input
-#.
-errF() {
-    assert -min "$#" 3 || return 255
-
-    # Check if $1 is a whole number
-    case :"$1${1#*[!0123456789]}" in
-        :) return 255 ;;
-        :00) : ;;
-        :0*) return 255 ;;
-        :"$1$1") : ;;
-        *) return 255 ;;
-    esac
-
-    [ "$1" -le 255 ] || return 255
-
-    _exit_code="$1"
-
-    if [ "$NO_COLOR" ]; then
-        case $2 in
-            '-')
-                shift 2
-                printf "%s\n" "$*" >&2
-            ;;
-            '--')
-                shift 2
-                printf "%s" "$*" >&2
-            ;;
-            '-1')
-                shift 2
-                printf "[%s] =>>: %s\n" "$(date "+%H:%M:%S")" "$*" >&2
-            ;;
-            '-2')
-                shift 2
-                printf "[%s] =>>: %s" "$(date "+%H:%M:%S")" "$*" >&2
-            ;;
-            *)
-                return 255
-            ;;
-        esac
-    else
-        case $2 in
-            '-')
-                shift 2
-                printf "%b%s%b\n" '\033[1;31m' "$*" '\033[0m' >&2
-            ;;
-            '--')
-                shift 2
-                printf "%b%s%b" '\033[1;31m' "$*" '\033[0m' >&2
-            ;;
-            '-1')
-                shift 2
-                printf "%b[%s] =>>: %b%s%b\n" '\033[1;31m' \
-                                              "$(date "+%H:%M:%S")" \
-                                              '\033[1;37m' "$*" '\033[0m' >&2
-            ;;
-            '-2')
-                shift 2
-                printf "%b[%s] =>>: %b%s%b" '\033[1;31m' \
-                                            "$(date "+%H:%M:%S")" \
-                                            '\033[1;37m' "$*" '\033[0m' >&2
-            ;;
-            *)
-                return 255
-            ;;
-        esac
-    fi
-
-    exit "$_exit_code"
-}
-
-#! .desc:
 # Print formatted text to stdout
 #! .params:
 # <$1> - color(
@@ -1504,7 +1417,7 @@ EPERMS() {
 EERROR() {
     assert -eq "$#" 1 || return 255
 
-    errF 235 -1 "EERROR: $1"
+    err -r -1 "EERROR: $1"; exit 235
 }
 
 # END custom_err_functions; 230-235
@@ -3265,11 +3178,11 @@ __loc_empty() {
 
         if [ "$silent_cmd" = 0 ]; then
             if ! rm -rf "$FILE_PATH"/*; then
-                errF 235 - 'rm: Failed.'
+                err -r - 'rm: Failed.'; exit 235
             fi
         else
             if ! rm -rf "$FILE_PATH"/* > /dev/null 2>&1; then
-                errF 235 - 'rm: Failed.'
+                err -r - 'rm: Failed.'; exit 235
             fi
         fi
     else
@@ -5849,19 +5762,19 @@ _clk_sync() {
         info -w - 'ntpd:'
 
         if ! ntpd -gGLnq pool.ntp.org; then
-            errF 235 - 'ntpd: Failed.'
+            err -r - 'ntpd: Failed.'; exit 235
         fi
 
         if ! hwclock -w; then
-            errF 235 - 'hwclock: Failed to set the system clock.'
+            err -r - 'hwclock: Failed to set the system clock.'; exit 235
         fi
     else
         if ! ntpd -gGLnq pool.ntp.org > /dev/null 2>&1; then
-            errF 235 - 'ntpd: Failed.'
+            err -r - 'ntpd: Failed.'; exit 235
         fi
 
         if ! hwclock -w > /dev/null 2>&1; then
-            errF 235 - 'hwclock: Failed to set the system clock.'
+            err -r - 'hwclock: Failed to set the system clock.'; exit 235
         fi
     fi
 }
@@ -6916,13 +6829,13 @@ _grub() {
                           --boot-directory="$efi_mnt"/EFI/BOOT \
                           --removable \
                           --no-nvram; then
-            errF 235 - 'grub-install: Failed.'
+            err -r - 'grub-install: Failed.'; exit 235
         fi
 
         info -w - 'grub-mkconfig:'
 
         if ! grub-mkconfig -o "$efi_mnt"/EFI/BOOT/grub/grub.cfg; then
-            errF 235 - 'grub-mkconfig: Failed.'
+            err -r - 'grub-mkconfig: Failed.'; exit 235
         fi
     else
         if ! grub-install --target=x86_64-efi \
@@ -6930,12 +6843,12 @@ _grub() {
                           --boot-directory="$efi_mnt"/EFI/BOOT \
                           --removable \
                           --no-nvram > /dev/null 2>&1; then
-            errF 235 - 'grub-install: Failed.'
+            err -r - 'grub-install: Failed.'; exit 235
         fi
 
         if ! grub-mkconfig -o "$efi_mnt"/EFI/BOOT/grub/grub.cfg \
              > /dev/null 2>&1; then
-            errF 235 - 'grub-mkconfig: Failed.'
+            err -r - 'grub-mkconfig: Failed.'; exit 235
         fi
     fi
 }
@@ -6999,12 +6912,12 @@ GRUB
         info -w - 'grub-mkconfig:'
 
         if ! grub-mkconfig -o "$efi_mnt"/EFI/BOOT/grub/grub.cfg; then
-            errF 235 - 'grub-mkconfig: Failed.'
+            err -r - 'grub-mkconfig: Failed.'; exit 235
         fi
     else
         if ! grub-mkconfig -o "$efi_mnt"/EFI/BOOT/grub/grub.cfg \
              > /dev/null 2>&1; then
-            errF 235 - 'grub-mkconfig: Failed.'
+            err -r - 'grub-mkconfig: Failed.'; exit 235
         fi
     fi
 }
@@ -7201,11 +7114,11 @@ MKINITCPIO_CONF
         info -w - 'mkinitcpio:'
 
         if ! mkinitcpio -P; then
-            errF 235 - 'mkinitcpio: Failed to regenerate initramfs.'
+            err -r - 'mkinitcpio: Failed to regenerate initramfs.'; exit 235
         fi
     else
         if ! mkinitcpio -P > /dev/null 2>&1; then
-            errF 235 - 'mkinitcpio: Failed to regenerate initramfs.'
+            err -r - 'mkinitcpio: Failed to regenerate initramfs.'; exit 235
         fi
     fi
 }
@@ -7839,11 +7752,11 @@ LOCALE_GEN
         info -w - 'locale-gen:'
 
         if ! locale-gen; then
-            errF 235 - 'locale-gen: Failed to generate locales.'
+            err -r - 'locale-gen: Failed to generate locales.'; exit 235
         fi
     else
         if ! locale-gen > /dev/null 2>&1; then
-            errF 235 - 'locale-gen: Failed to generate locales.'
+            err -r - 'locale-gen: Failed to generate locales.'; exit 235
         fi
     fi
 }
@@ -8028,12 +7941,12 @@ _nvram_clr() {
     if [ "$silent_cmd" = 0 ]; then
         if ! rm -f '/sys/firmware/efi/efivars'/BootOrder* \
                    '/sys/firmware/efi/efivars'/Boot0*; then
-            errF 235 - 'rm: Failed.'
+            err -r - 'rm: Failed.'; exit 235
         fi
     else
         if ! rm -f '/sys/firmware/efi/efivars'/BootOrder* \
                    '/sys/firmware/efi/efivars'/Boot0* > /dev/null 2>&1; then
-            errF 235 - 'rm: Failed.'
+            err -r - 'rm: Failed.'; exit 235
         fi
     fi
 
@@ -8774,7 +8687,7 @@ MIRRORLIST
         FILE="$FILE$LF"
     else
         err -r - 'reflector: Failed.'
-        errF 235 - 'Try again on a static network condition.'
+        err -r - 'Try again on a static network condition.'; exit 235
     fi
 
     __file_write_overwrite;
@@ -8820,7 +8733,7 @@ MIRRORLIST
         FILE="$FILE$LF"
     else
         err -r - 'reflector: Failed.'
-        errF 235 - 'Try again on a static network condition.'
+        err -r - 'Try again on a static network condition.'; exit 235
     fi
 
     __file_write_overwrite;
@@ -9711,11 +9624,11 @@ LOCALTIME
 
     if [ "$silent_cmd" = 0 ]; then
         if ! hwclock -w; then
-            errF 235 - 'hwclock: Failed to set the system clock.'
+            err -r - 'hwclock: Failed to set the system clock.'; exit 235
         fi
     else
         if ! hwclock -w > /dev/null 2>&1; then
-            errF 235 - 'hwclock: Failed to set the system clock.'
+            err -r - 'hwclock: Failed to set the system clock.'; exit 235
         fi
     fi
 }
@@ -9738,11 +9651,11 @@ LOCALTIME
 
     if [ "$silent_cmd" = 0 ]; then
         if ! hwclock -w; then
-            errF 235 - 'hwclock: Failed to set the system clock.'
+            err -r - 'hwclock: Failed to set the system clock.'; exit 235
         fi
     else
         if ! hwclock -w > /dev/null 2>&1; then
-            errF 235 - 'hwclock: Failed to set the system clock.'
+            err -r - 'hwclock: Failed to set the system clock.'; exit 235
         fi
     fi
 }
@@ -10065,7 +9978,7 @@ main() {
     # end arg parsing; main()
 
     [ "$(id -u)" = 0 ] || {
-        errF 1 - 'Missing root rights.'
+        err -r - 'Missing root rights.'; exit 1
     }
 
     LC_ALL=C; export LC_ALL
@@ -10091,12 +10004,20 @@ main() {
         set -e
 
         # env setup
-        mkdir -p "$tmpd" || errF "$?" - "Cannot create tmpd: $tmpd"
+        { mkdir -p "$tmpd"; } || {
+            set -- "$?"
+            err -r - "Cannot create tmpd: $tmpd"
+            exit "$1"
+        }
         { : > "$tmpf" && chmod 0600 "$tmpf"; } || {
-            errF "$?" - "Cannot create tmpf: $tmpf"
+            set -- "$?"
+            err -r - "Cannot create tmpf: $tmpf"
+            exit "$1"
         }
         { : > "$logf" && chmod 0600 "$logf"; } || {
-            errF "$?" - "Cannot create logf: $logf"
+            set -- "$?"
+            err -r - "Cannot create logf: $logf"
+            exit "$1"
         }
 
         eval "info -be -1 \"$1 -> ${opd}()\"; $opd"
