syscfg: Add pluggable hint override mechanism
Signed-off-by: Dimitar Yurukov <mscalindt@protonmail.com>

diff --git a/src/syscfg b/src/syscfg
--- a/src/syscfg
+++ b/src/syscfg
@@ -385,11 +385,29 @@ fs_equiv_type_attr() {
 #
 # Hint `--` will be respected at all times.
 #
-# For more information, refer to the documentation of hint_set().
+# For more information, refer to the documentation of hint_act() and
+# hint_set().
 #.
 hint() {
     assert -min "$#" 2 || exit 255
     assert -whole-n "$1" || exit 255
+
+    # Let an independent implementation dictate the outcome. This could be
+    # desirable when, for example, a hint is to be enabled (or disabled)
+    # globally.
+    #
+    # By default, it is expected hint_act() to return false to proceed with
+    # the original hint query logic. Shall hint_act() return true, it is
+    # required that $_act is set to either `0` or `1` to fulfill the outcome.
+    if hint_act "$2"; then
+        case "$_act" in
+            0|1) return "$_act" ;;
+        esac
+
+        err -red - '${0##*/}: Invalid hint action:' "$_act"
+
+        exit 255
+    fi
 
     _hint="$2"; shift "$((2 + $1))"
 
@@ -411,6 +429,25 @@ hint() {
         return 0
     done
 
+    return 1
+}
+
+#! .desc:
+# Dictate the outcome of a hint query independently
+#! .params:
+# <$1> - hint
+#! .gives.var:
+# (0) <_act> - integer;
+#              `0` = act true; `1` = act false
+#! .rc:
+# (0) true
+# (1) false
+#! .desc.ext:
+# This function exists to aid in modifying behavior modularly.
+#
+# For more information, refer to the documentation of hint().
+#.
+hint_act() {
     return 1
 }
 
