syscfg: Remove hint `-log-fed`
`-log-fed` is not an independent hint; is replaced by `-color`.

Signed-off-by: Dimitar Yurukov <mscalindt@protonmail.com>

diff --git a/src/syscfg b/src/syscfg
--- a/src/syscfg
+++ b/src/syscfg
@@ -434,12 +434,12 @@ hint() {
 #! .desc.ext:
 # Recognized hints:
 # `--`: End of hints;
+# `-color`: Use color;
 # `-crc`, <string>: CRC32 string;
 # `-del`: 'Delete' action/operation;
 # `-gid`, <string>: Group ID;
 # `-group`, <string>: Group name;
 # `-log`, <file path>: Log file path;
-# `-log-fed`, <file path>: Log file path with fed() format;
 # `-mode`, <[string]>: Octal mode;
 # `-no-avoid`: No write avoidance;
 # `-no-sanit`: No environment sanitization;
@@ -460,7 +460,8 @@ hint_set() {
     shift "$((1 + $1))"
 
     case "$1" in
-        '--' | '-del' | '-no-avoid' | '-no-sanit' | '-out-req' | '-trunc')
+        '--' | '-color' | '-del' | '-no-avoid' | '-no-sanit' | '-out-req' | \
+        '-trunc')
             _hint="$1"
             _hint_arg=
             _offset=1
@@ -481,8 +482,7 @@ hint_set() {
 
             return 0
         ;;
-        '-crc' | '-gid' | '-group' | '-log' | '-log-fed' | '-out-save' | \
-        '-uid' | '-user')
+        '-crc' | '-gid' | '-group' | '-log' | '-out-save' | '-uid' | '-user')
             [ "$2" ] || {
                 err -red - '${0##*/}: Missing argument specification:' "$1"
 
@@ -653,7 +653,7 @@ write_info() {
         '-o') __info -white - 'Will write a binary file:' ;;
     esac
 
-    if hint 4 -log-fed "$@"; then
+    if hint 4 -log "$@"; then
         case "$1$4" in
             '-w-f') __info -white - 'Will update a file (OW_HARD):' ;;
             '-w-o') __info -white - 'Will update a file (OW_SOFT):' ;;
@@ -738,11 +738,7 @@ write_info_avoidance() {
 # For more information, refer to the documentation of __write().
 #.
 write_info_stat() {
-    if hint 4 -log "$@"; then
-        while IFS= read -r _line || [ "$_line" ]; do
-            info - - "$1"
-        done < "$_hint"
-    elif hint 4 -log-fed "$@"; then
+    if hint 4 -color "$@" && hint 4 -log "$@"; then
         while IFS=" " read -r _n _line || [ "$_line" ]; do
             set -- "$_line"
 
@@ -750,6 +746,10 @@ write_info_stat() {
                 *'+') info -green -- "$_n " && info - - "$1" ;;
                 *'-') info -red -- "$_n " && info - - "$1" ;;
             esac
+        done < "$_hint"
+    elif hint 4 -log "$@"; then
+        while IFS= read -r _line || [ "$_line" ]; do
+            info - - "$1"
         done < "$_hint"
     else
         case "$1" in
@@ -1233,14 +1233,14 @@ __obj_write_ow_soft() {
 # (255) input error
 #! .desc.ext:
 # Supported hints:
+# `-color`: Colorized parse of the `-log` file, assuming fed() format;
 # `-gid`: Specify GID to assert/set;
 # `-group`: Specify group name to assert/set;
-# `-log`: Use a specified file path for write statistics;
-# `-log-fed`: Use a specified file path for colored write statistics;
+# `-log`: Specify file path for write statistics;
 # `-mode`: File mode in octal to assert/set;
 # `-no-avoid`: Disable write avoidance;
 # `-no-sanit`: Preserve $OBJ and $OBJ_PATH;
-# '-trunc': Truncate `-log`/`-log-fed` specified paths;
+# '-trunc': Truncate the path specified by `-log`;
 # `-uid`: Specify UID to assert/set;
 # `-user`: Specify user name to assert/set.
 #
@@ -1325,14 +1325,12 @@ __write() {
         ;;
     esac
 
-    if hint 4 -trunc "$@"; then
-        if hint 4 -log "$@" || hint 4 -log-fed "$@"; then
-            { : > "$_hint"; } || {
-                err -white - 'Failed to truncate the log file.'
+    if hint 4 -trunc "$@" && hint 4 -log "$@"; then
+        { : > "$_hint"; } || {
+            err -white - 'Failed to truncate the log file.'
 
-                return 1
-            }
-        fi
+            return 1
+        }
     fi
 
     if hint 4 -no-sanit "$@"; then
