syscfg: Gracefully handle a missing specified log
Even with correct usage of the syscfg APIs, this situation can happen
when an object contains no changes (thus no log) but a write is valid,
likely due to object inequivalence (fs_equiv() return `1`).

Signed-off-by: Dimitar Yurukov <mscalindt@protonmail.com>

diff --git a/src/syscfg b/src/syscfg
--- a/src/syscfg
+++ b/src/syscfg
@@ -777,6 +777,12 @@ write_info_avoidance() {
 #.
 write_info_stat() {
     if hint 4 -color "$@" && hint 4 -log "$@"; then
+        if [ ! -e "$_hint" ]; then
+            __info -yellow - 'No log available.'
+
+            return 0
+        fi
+
         while IFS=" " read -r _n _line || [ "$_line" ]; do
             set -- "$_line"
 
@@ -786,6 +792,12 @@ write_info_stat() {
             esac
         done < "$_hint"
     elif hint 4 -log "$@"; then
+        if [ ! -e "$_hint" ]; then
+            __info -yellow - 'No log available.'
+
+            return 0
+        fi
+
         while IFS= read -r _line || [ "$_line" ]; do
             info - - "$1"
         done < "$_hint"
@@ -1362,20 +1374,24 @@ __write() {
     esac
 
     if hint 4 -trunc "$@" && hint 4 -log "$@"; then
-        { : > "$_hint"; } || {
-            err -white - "Failed to truncate the log file. ($?)"
+        if [ -e "$_hint" ]; then
+            { : > "$_hint"; } || {
+                err -white - "Failed to truncate the log file. ($?)"
 
-            return 1
-        }
+                return 1
+            }
+        fi
     fi
 
     if hint 4 -sanit "$@"; then
         if hint 4 -log "$@"; then
-            rm -rf "$_hint" || {
-                err -white - "Failed to delete the log file. ($?)"
+            if [ -e "$_hint" ]; then
+                rm -rf "$_hint" || {
+                    err -white - "Failed to delete the log file. ($?)"
 
-                return 1
-            }
+                    return 1
+                }
+            fi
         fi
 
         unset OBJ OBJ_PATH
