syscfg: [__dir_target_write_overwrite()] deprecate 'SYMLINK'
In favor of 0fde16de8208 [1] and 11f53931a9b6 [2].

[1] syscfg: Add __loc_target_link_overwrite()
[2] syscfg: Use __loc_target_link_overwrite() for symlinks

Signed-off-by: Dimitar Yurukov <mscalindt@protonmail.com>

diff --git a/src/syscfg b/src/syscfg
--- a/src/syscfg
+++ b/src/syscfg
@@ -2452,11 +2452,6 @@ __dir_target_write() {
 
 #! .desc:
 # Copy a directory at the specified path (overwrite path)
-#! .params:
-# [$1] - type(
-#     'SYMLINK' - symbolic copy
-#     .
-# )
 #! .uses:
 # <FILE_PATH> $ - the directory
 # <FILE_PATH_TARGET> $ - the path to write the directory at
@@ -2492,46 +2487,31 @@ __dir_target_write_overwrite() {
         fi
 
         if [ "$logging" = 1 ]; then
-            if [ "$1" = 'SYMLINK' ]; then
-                info -w -1 'Will symlink to/from:'
-                info -w -- 'D '; info - - "$FILE_PATH"
-                info -w -- 'D '; info - - "$FILE_PATH_TARGET"
-            else
-                info -w -1 'Will copy from/to:'
-                info -w -- 'D '; info - - "$FILE_PATH"
-                info -w -- 'D '; info - - "$FILE_PATH_TARGET"
+            info -w -1 'Will copy from/to:'
+            info -w -- 'D '; info - - "$FILE_PATH"
+            info -w -- 'D '; info - - "$FILE_PATH_TARGET"
 
-                info -w -- '> '
-                find "$FILE_PATH"//. ! -name . | \
-                    grep -c // 2> /dev/null | \
-                        while IFS= read -r _line0; do
-                            printf "%s, " "$_line0"
+            info -w -- '> '
+            find "$FILE_PATH"//. ! -name . | grep -c // 2> /dev/null | \
+                while IFS= read -r _line0; do
+                    printf "%s, " "$_line0"
 
-                            info -w -- 'D '
-                            find "$FILE_PATH"//. ! -name . -type d | \
-                                grep -c // 2> /dev/null | \
-                                    while IFS= read -r _line1; do
-                                        printf "%s, " "$_line1"
+                    info -w -- 'D '
+                    find "$FILE_PATH"//. ! -name . -type d | \
+                        grep -c // 2> /dev/null | \
+                            while IFS= read -r _line1; do
+                                printf "%s, " "$_line1"
 
-                                        info -w -- 'F '
-                                        info - - "$((_line0 - _line1))"
-                                    done
-                        done
-            fi
+                                info -w -- 'F '
+                                info - - "$((_line0 - _line1))"
+                            done
+                done
         fi
 
-        if [ "$1" = 'SYMLINK' ]; then
-            if ! loc_link "$FILE_PATH" "$FILE_PATH_TARGET"; then
-                err -r -1 'Write error:'
-                err -r -- 'D '; err - - "$FILE_PATH_TARGET"
-                exit 201
-            fi
-        else
-            if ! dir_write "$FILE_PATH" "$FILE_PATH_TARGET"; then
-                err -r -1 'Write error:'
-                err -r -- 'D '; err - - "$FILE_PATH_TARGET"
-                exit 201
-            fi
+        if ! dir_write "$FILE_PATH" "$FILE_PATH_TARGET"; then
+            err -r -1 'Write error:'
+            err -r -- 'D '; err - - "$FILE_PATH_TARGET"
+            exit 201
         fi
     break; done
 
