__write(): Support hint `-sanit`
Signed-off-by: Dimitar Yurukov <mscalindt@protonmail.com>

diff --git a/src/syscfg b/src/syscfg
--- a/src/syscfg
+++ b/src/syscfg
@@ -445,6 +445,7 @@ hint() {
 # `-no-sanit`: No environment sanitization;
 # `-out-save`, <variable name>: Save &1 (stdout);
 # `-req-out`: Require &1 (stdout);
+# `-sanit`: Environment sanitization;
 # `-trunc`: 'Truncate' action/operation;
 # `-uid`, <string>: User ID;
 # `-user`, <string>: User name.
@@ -461,7 +462,7 @@ hint_set() {
 
     case "$1" in
         '--' | '-color' | '-del' | '-no-avoid' | '-no-sanit' | '-req-out' | \
-        '-trunc')
+        '-sanit' | '-trunc')
             _hint="$1"
             _hint_arg=
             _offset=1
@@ -1237,6 +1238,7 @@ __obj_write_ow_soft() {
 # `-mode`: Specify file mode in octal to assert/set;
 # `-no-avoid`: Disable write avoidance;
 # `-no-sanit`: Preserve $OBJ and $OBJ_PATH;
+# `-sanit`: Delete hint paths, unset $OBJ and $OBJ_PATH;
 # '-trunc': Truncate the path specified by `-log`;
 # `-uid`: Specify UID to assert/set;
 # `-user`: Specify user name to assert/set.
@@ -1330,7 +1332,17 @@ __write() {
         }
     fi
 
-    if hint 4 -no-sanit "$@"; then
+    if hint 4 -sanit "$@"; then
+        if hint 4 -log "$@"; then
+            rm -rf "$_hint" || {
+                err -white - 'Failed to delete the log file.'
+
+                return 1
+            }
+        fi
+
+        unset OBJ OBJ_PATH
+    elif hint 4 -no-sanit "$@"; then
         OBJ="$2"; OBJ_PATH="$3"
     fi
 
