syscfg: [__loc_delete()] add missing error handling
Fixes missing error handling when $silent=1.

Signed-off-by: Dimitar Yurukov <mscalindt@protonmail.com>

diff --git a/src/syscfg b/src/syscfg
--- a/src/syscfg
+++ b/src/syscfg
@@ -3480,7 +3480,11 @@ __loc_delete() {
             exit 201
         fi
     else
-        loc_delete "$FILE_PATH" > /dev/null 2>&1
+        if ! loc_delete "$FILE_PATH" > /dev/null 2>&1; then
+            err -r -1 'Removal error:'
+            err -r -- '> '; err - - "$FILE_PATH"
+            exit 201
+        fi
     fi
 }
 
