syscfg: Add and use __file_write_overwrite_soft()
Required for a true, filesystem overwrite; for example, in the kernel's
sysfs.

Signed-off-by: Dimitar Yurukov <mscalindt@protonmail.com>

diff --git a/src/syscfg b/src/syscfg
--- a/src/syscfg
+++ b/src/syscfg
@@ -2084,6 +2084,31 @@ file_write() {
 }
 
 #! .desc:
+# Forcefully write a given string at a path
+#! .params:
+# <"$1"> - absolute path
+# <"$2"> - string
+#! .rc:
+# (0) success
+# (*) error
+# (255) bad input
+#.
+file_writeF() {
+    assert -eq "$#" 2 || return 255
+
+    if exist "$1"; then
+        chattr_remove "$1" 2> /dev/null || :
+        unmount "$1" 2> /dev/null || :
+
+        rm -rf "$1" 2> /dev/null || :
+    fi
+
+    mkdir_parents "$1"
+
+    { printf "%s" "$2" > "$1"; } 2> /dev/null
+}
+
+#! .desc:
 # Write a given octal sequence at a path
 #! .params:
 # <"$1"> - absolute path
@@ -2612,6 +2637,71 @@ __file_write() {
 #.
 __file_write_overwrite() {
     __loc_delete && __file_write;
+}
+
+#! .desc:
+# Overwrite a file at the specified path
+#! .uses:
+# <FILE> $ - the file
+# <FILE_PATH> $ - the path to write the file at
+#! .rc:
+# (0) success
+# (*) error
+# (255) bad usage
+#.
+__file_write_overwrite_soft() {
+    if [ ! "$FILE_PATH" ]; then
+        _err -red - 'Missing FILE_PATH.'
+        return 255
+    fi
+
+    if [ ! "$FILE" ]; then
+        _info -white - 'Empty FILE. File write cancelled:'
+        ftype "$FILE_PATH" -info || :
+        info - - " $FILE_PATH"
+        return 0
+    fi
+
+    while :; do
+        if [ "$always_write" = 0 ]; then
+            if file_equiv "$FILE_PATH" "$FILE"; then
+                _info -white - 'File write avoided:'
+                ftype "$FILE_PATH" -info || :
+                info - - " $FILE_PATH"
+                break
+            fi
+        fi
+
+        if LOG_written; then
+            _info -white - 'File changes:'
+            ftype "$FILE_PATH" -info || :
+            info - - " $FILE_PATH"
+            LOG_print;
+        else
+            _info -white - 'Will overwrite a file:'
+            ftype "$FILE_PATH" -info || :
+            info - - " $FILE_PATH"
+            if [ "$silent_write" = 0 ]; then
+                info -white - '0:'; info - -- "$FILE"
+            fi
+        fi
+
+        if ! file_writeF "$FILE_PATH" "$FILE"; then
+            _err -red - 'File overwrite error:'
+            ftype "$FILE_PATH" -err || :
+            err - - " $FILE_PATH"
+            exit 1
+        fi
+    break; done
+
+    if ! loc_own_user "$FILE_PATH"; then
+        EERROR 'Failed to set user permissions.'
+    fi
+
+    if ! LOG_clear; then
+        _err -r - 'Log clear error.'
+        exit 1
+    fi
 }
 
 #! .desc:
@@ -6446,7 +6536,7 @@ SCALING_GOVERNOR
 performance
 SCALING_GOVERNOR
 
-        __file_write_overwrite;
+        __file_write_overwrite_soft;
     done
 }
 
@@ -6474,7 +6564,7 @@ SCALING_GOVERNOR
 schedutil
 SCALING_GOVERNOR
 
-        __file_write_overwrite;
+        __file_write_overwrite_soft;
     done
 }
 
